language: node_js
node_js:
- 11.1
- 10
- 8
git:
  depth: 3
after_success:
- npm run coverage
- npm run build
script:
- npm run test
deploy:
  provider: npm
  email: i@charugin.ru
  api_key:
    secure: HwEoiXJucL4QhNVBVep4jlEspKZCdQ7XGGOIenpDNHJtLx4YOTCRpzrnTPsBsfmlv5ejDPtdWe0/2WvTRkoIk31eH/b7qPoll9xNmhSRxcL74RH3DdQEL6QO30rxhTyBYACnZylNtnzD2Sx6z1sGUsJpSZq4XbaueS1pfItXFyMsKNiJL7MJWRSRJ2JhaP4Ync8za1kREg9yQUCKv9Jojew8DN1v4x3WfMVBe5Fi/PAz1h+Zksd1wjDVP5DAhCau3ZkrYIgLPE09HwtN+rWPD4V5saRxSol/h2vtRvZDosw46cJcEcOSZRLLyZWZGfNQ0CAVJ9lEjQIImcpWdbEIIGYzvUNyQ6c5HHOIqt7fzx6GNJbxb+ZJHp4OYNcwrnOlWQByHcK8uu+nT5SNX2FnqIFG7gXLByFVFEzBHAUaRTlt2YxEOW0qJvx5wYNf1rQ9iXISn6BGIObsHouWDZ7ilAkdpgWlAizSj6qnZZHWM7MsIj8Q9wJmLXyrGvFrec9+GTNWfl9jOMQ+LdW+NiB78heGkgWJmehH740IktWpCNwm1c6zW0RQLjf1HKthEXti9QLAQf0a+MGjhpYZTcgGU65F6SKFmIhbRNpj0roN24F9eJqCOSit/S7rrKjRovdpUOu7KwwKpuSqdIz/gwRqcjQRl8jqI3RG/Q2z4FBjtRU=
  on:
    tags: true
    repo: RomiC/query-cast
  skip_cleanup: true
