name: Tests

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "18", "20"]
    name: Test with node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Installing dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Testing
        run: npm test
      - name: Calculating coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: node v${{ matrix.node }}
          parallel: true
      - name: Creating a test build
        run: npm run build

  finish:
    needs: test
    runs-on: ubuntu-latest
    name: Publishing coverage report
    steps:
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true